<?php
// database/seeders/MetaAdsSeeder.php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MetaAdsSeeder extends Seeder
{
    public function run(): void
    {
        $templates = [
            [
                'name'                  => 'Students',
                'slug'                  => 'students',
                'industry'              => 'Education',
                'description'           => 'College and university students aged 18–24',
                'objective'             => 'LEAD_GENERATION',
                'age_min'               => 18,
                'age_max'               => 24,
                'genders'               => 'all',
                'interests'             => json_encode([
                    ['id' => '6003139266461', 'name' => 'Higher education'],
                    ['id' => '6003020834693', 'name' => 'College'],
                    ['id' => '6003397426735', 'name' => 'University'],
                    ['id' => '6003115125831', 'name' => 'Student'],
                ]),
                'targeting_json'        => json_encode([
                    'age_min'                => 18,
                    'age_max'                => 24,
                    'flexible_spec'          => [[
                        'interests' => [
                            ['id' => '6003139266461', 'name' => 'Higher education'],
                            ['id' => '6003020834693', 'name' => 'College'],
                        ],
                    ]],
                ]),
                'suggested_daily_budget'=> 300,
                'estimated_reach_min'   => 50000,
                'estimated_reach_max'   => 200000,
                'sort_order'            => 1,
            ],
            [
                'name'                  => 'Job seekers',
                'slug'                  => 'job-seekers',
                'industry'              => 'Career',
                'description'           => 'People actively looking for jobs, 20–35',
                'objective'             => 'LEAD_GENERATION',
                'age_min'               => 20,
                'age_max'               => 35,
                'genders'               => 'all',
                'interests'             => json_encode([
                    ['id' => '6003284416927', 'name' => 'Job hunting'],
                    ['id' => '6003006343721', 'name' => 'Career development'],
                    ['id' => '6002839668884', 'name' => 'LinkedIn'],
                ]),
                'targeting_json'        => json_encode([
                    'age_min' => 20, 'age_max' => 35,
                    'flexible_spec' => [[ 'interests' => [['id' => '6003284416927', 'name' => 'Job hunting']] ]],
                ]),
                'suggested_daily_budget'=> 400,
                'estimated_reach_min'   => 80000,
                'estimated_reach_max'   => 300000,
                'sort_order'            => 2,
            ],
            [
                'name'                  => 'Small business owners',
                'slug'                  => 'small-business-owners',
                'industry'              => 'Business',
                'description'           => 'Entrepreneurs and SME owners, 25–55',
                'objective'             => 'LEAD_GENERATION',
                'age_min'               => 25,
                'age_max'               => 55,
                'genders'               => 'all',
                'interests'             => json_encode([
                    ['id' => '6003200426513', 'name' => 'Small business'],
                    ['id' => '6002839294632', 'name' => 'Entrepreneurship'],
                    ['id' => '6003348059834', 'name' => 'Business owner'],
                ]),
                'targeting_json'        => json_encode([
                    'age_min' => 25, 'age_max' => 55,
                    'flexible_spec' => [[ 'interests' => [['id' => '6003200426513', 'name' => 'Small business']] ]],
                ]),
                'suggested_daily_budget'=> 600,
                'estimated_reach_min'   => 40000,
                'estimated_reach_max'   => 180000,
                'sort_order'            => 3,
            ],
            [
                'name'                  => 'Online shoppers',
                'slug'                  => 'online-shoppers',
                'industry'              => 'E-commerce',
                'description'           => 'Frequent online shoppers, 18–45',
                'objective'             => 'CONVERSIONS',
                'age_min'               => 18,
                'age_max'               => 45,
                'genders'               => 'all',
                'behaviors'             => json_encode([
                    ['id' => '6071631541183', 'name' => 'Engaged shoppers'],
                    ['id' => '6002714895372', 'name' => 'Online shopping'],
                ]),
                'targeting_json'        => json_encode([
                    'age_min' => 18, 'age_max' => 45,
                    'flexible_spec' => [[ 'behaviors' => [['id' => '6071631541183', 'name' => 'Engaged shoppers']] ]],
                ]),
                'suggested_daily_budget'=> 500,
                'estimated_reach_min'   => 100000,
                'estimated_reach_max'   => 500000,
                'sort_order'            => 4,
            ],
            [
                'name'                  => 'Real estate buyers',
                'slug'                  => 'real-estate-buyers',
                'industry'              => 'Real Estate',
                'description'           => 'People interested in buying property, 25–60',
                'objective'             => 'LEAD_GENERATION',
                'age_min'               => 25,
                'age_max'               => 60,
                'genders'               => 'all',
                'interests'             => json_encode([
                    ['id' => '6003022722610', 'name' => 'Real estate'],
                    ['id' => '6003091862897', 'name' => 'Property'],
                    ['id' => '6003029836635', 'name' => 'Home loan'],
                ]),
                'targeting_json'        => json_encode([
                    'age_min' => 25, 'age_max' => 60,
                    'flexible_spec' => [[ 'interests' => [['id' => '6003022722610', 'name' => 'Real estate']] ]],
                ]),
                'suggested_daily_budget'=> 800,
                'estimated_reach_min'   => 30000,
                'estimated_reach_max'   => 150000,
                'sort_order'            => 5,
            ],
            [
                'name'                  => 'Parents',
                'slug'                  => 'parents',
                'industry'              => 'Family',
                'description'           => 'Parents of young children, 25–50',
                'objective'             => 'REACH',
                'age_min'               => 25,
                'age_max'               => 50,
                'genders'               => 'all',
                'behaviors'             => json_encode([['id' => '6020899490066', 'name' => 'Parents']]),
                'targeting_json'        => json_encode([
                    'age_min' => 25, 'age_max' => 50,
                    'flexible_spec' => [[ 'behaviors' => [['id' => '6020899490066', 'name' => 'Parents']] ]],
                ]),
                'suggested_daily_budget'=> 400,
                'estimated_reach_min'   => 80000,
                'estimated_reach_max'   => 350000,
                'sort_order'            => 6,
            ],
            [
                'name'                  => 'Fitness enthusiasts',
                'slug'                  => 'fitness-enthusiasts',
                'industry'              => 'Health & Fitness',
                'description'           => 'Gym, yoga, and fitness lovers, 18–45',
                'objective'             => 'LEAD_GENERATION',
                'age_min'               => 18,
                'age_max'               => 45,
                'genders'               => 'all',
                'interests'             => json_encode([
                    ['id' => '6003483915030', 'name' => 'Physical fitness'],
                    ['id' => '6003107902433', 'name' => 'Gym'],
                    ['id' => '6003268994073', 'name' => 'Yoga'],
                    ['id' => '6002882279870', 'name' => 'Nutrition'],
                ]),
                'targeting_json'        => json_encode([
                    'age_min' => 18, 'age_max' => 45,
                    'flexible_spec' => [[ 'interests' => [['id' => '6003483915030', 'name' => 'Physical fitness'], ['id' => '6003107902433', 'name' => 'Gym']] ]],
                ]),
                'suggested_daily_budget'=> 500,
                'estimated_reach_min'   => 60000,
                'estimated_reach_max'   => 250000,
                'sort_order'            => 7,
            ],
            [
                'name'                  => 'Food & restaurant lovers',
                'slug'                  => 'food-restaurant-lovers',
                'industry'              => 'Food & Beverage',
                'description'           => 'Foodies and restaurant goers, 18–55',
                'objective'             => 'REACH',
                'age_min'               => 18,
                'age_max'               => 55,
                'genders'               => 'all',
                'interests'             => json_encode([
                    ['id' => '6003107902429', 'name' => 'Food'],
                    ['id' => '6003009645975', 'name' => 'Restaurants'],
                    ['id' => '6003148785839', 'name' => 'Food delivery'],
                ]),
                'targeting_json'        => json_encode([
                    'age_min' => 18, 'age_max' => 55,
                    'flexible_spec' => [[ 'interests' => [['id' => '6003107902429', 'name' => 'Food']] ]],
                ]),
                'suggested_daily_budget'=> 400,
                'sort_order'            => 8,
            ],
            [
                'name'                  => 'Automobile buyers',
                'slug'                  => 'automobile-buyers',
                'industry'              => 'Automotive',
                'description'           => 'Car and bike buyers, 20–55',
                'objective'             => 'LEAD_GENERATION',
                'age_min'               => 20,
                'age_max'               => 55,
                'genders'               => 'all',
                'interests'             => json_encode([
                    ['id' => '6002839315738', 'name' => 'Automotive'],
                    ['id' => '6003018615629', 'name' => 'Car'],
                    ['id' => '6003157295556', 'name' => 'Motorcycle'],
                ]),
                'targeting_json'        => json_encode([
                    'age_min' => 20, 'age_max' => 55,
                    'flexible_spec' => [[ 'interests' => [['id' => '6002839315738', 'name' => 'Automotive']] ]],
                ]),
                'suggested_daily_budget'=> 700,
                'estimated_reach_min'   => 50000,
                'estimated_reach_max'   => 200000,
                'sort_order'            => 9,
            ],
            [
                'name'                  => 'Tech enthusiasts',
                'slug'                  => 'tech-enthusiasts',
                'industry'              => 'Technology',
                'description'           => 'Software, gadget, and tech lovers, 18–45',
                'objective'             => 'LINK_CLICKS',
                'age_min'               => 18,
                'age_max'               => 45,
                'genders'               => 'all',
                'interests'             => json_encode([
                    ['id' => '6004060397054', 'name' => 'Technology'],
                    ['id' => '6003139266451', 'name' => 'Software'],
                    ['id' => '6003283067963', 'name' => 'Gadget'],
                ]),
                'targeting_json'        => json_encode([
                    'age_min' => 18, 'age_max' => 45,
                    'flexible_spec' => [[ 'interests' => [['id' => '6004060397054', 'name' => 'Technology']] ]],
                ]),
                'suggested_daily_budget'=> 500,
                'sort_order'            => 10,
            ],
            [
                'name'                  => 'Fashion & beauty',
                'slug'                  => 'fashion-beauty',
                'industry'              => 'Fashion',
                'description'           => 'Fashion, clothing, and beauty shoppers, 18–40',
                'objective'             => 'CONVERSIONS',
                'age_min'               => 18,
                'age_max'               => 40,
                'genders'               => 'female',
                'interests'             => json_encode([
                    ['id' => '6003137437855', 'name' => 'Fashion'],
                    ['id' => '6003006183930', 'name' => 'Beauty'],
                    ['id' => '6002839319686', 'name' => 'Clothing'],
                ]),
                'targeting_json'        => json_encode([
                    'age_min' => 18, 'age_max' => 40, 'genders' => [2],
                    'flexible_spec' => [[ 'interests' => [['id' => '6003137437855', 'name' => 'Fashion']] ]],
                ]),
                'suggested_daily_budget'=> 500,
                'sort_order'            => 11,
            ],
            [
                'name'                  => 'Healthcare & wellness',
                'slug'                  => 'healthcare-wellness',
                'industry'              => 'Healthcare',
                'description'           => 'Health-conscious people, 25–60',
                'objective'             => 'LEAD_GENERATION',
                'age_min'               => 25,
                'age_max'               => 60,
                'genders'               => 'all',
                'interests'             => json_encode([
                    ['id' => '6003396586162', 'name' => 'Health'],
                    ['id' => '6003006143691', 'name' => 'Wellness'],
                    ['id' => '6003300547463', 'name' => 'Medical'],
                ]),
                'targeting_json'        => json_encode([
                    'age_min' => 25, 'age_max' => 60,
                    'flexible_spec' => [[ 'interests' => [['id' => '6003396586162', 'name' => 'Health']] ]],
                ]),
                'suggested_daily_budget'=> 600,
                'sort_order'            => 12,
            ],
            [
                'name'                  => 'Education & learning',
                'slug'                  => 'education-learning',
                'industry'              => 'Education',
                'description'           => 'Online courses and self-improvement, 18–55',
                'objective'             => 'LEAD_GENERATION',
                'age_min'               => 18,
                'age_max'               => 55,
                'genders'               => 'all',
                'interests'             => json_encode([
                    ['id' => '6003139266453', 'name' => 'Online education'],
                    ['id' => '6003107902435', 'name' => 'E-learning'],
                    ['id' => '6002839315724', 'name' => 'Self-improvement'],
                ]),
                'targeting_json'        => json_encode([
                    'age_min' => 18, 'age_max' => 55,
                    'flexible_spec' => [[ 'interests' => [['id' => '6003139266453', 'name' => 'Online education']] ]],
                ]),
                'suggested_daily_budget'=> 500,
                'sort_order'            => 13,
            ],
            [
                'name'                  => 'Travellers',
                'slug'                  => 'travellers',
                'industry'              => 'Travel',
                'description'           => 'Frequent travellers, 18–60',
                'objective'             => 'LINK_CLICKS',
                'age_min'               => 18,
                'age_max'               => 60,
                'genders'               => 'all',
                'behaviors'             => json_encode([['id' => '6002714895572', 'name' => 'Frequent international travellers']]),
                'interests'             => json_encode([
                    ['id' => '6003107902428', 'name' => 'Travel'],
                    ['id' => '6003300547469', 'name' => 'Tourism'],
                    ['id' => '6003284416929', 'name' => 'Hotels'],
                ]),
                'targeting_json'        => json_encode([
                    'age_min' => 18, 'age_max' => 60,
                    'flexible_spec' => [[ 'interests' => [['id' => '6003107902428', 'name' => 'Travel']] ]],
                ]),
                'suggested_daily_budget'=> 600,
                'sort_order'            => 14,
            ],
            [
                'name'                  => 'Luxury buyers',
                'slug'                  => 'luxury-buyers',
                'industry'              => 'Luxury',
                'description'           => 'Premium product buyers, 25–60',
                'objective'             => 'CONVERSIONS',
                'age_min'               => 25,
                'age_max'               => 60,
                'genders'               => 'all',
                'interests'             => json_encode([
                    ['id' => '6003283067957', 'name' => 'Luxury goods'],
                    ['id' => '6002839298878', 'name' => 'Premium brands'],
                ]),
                'targeting_json'        => json_encode([
                    'age_min' => 25, 'age_max' => 60,
                    'flexible_spec' => [[ 'interests' => [['id' => '6003283067957', 'name' => 'Luxury goods']] ]],
                ]),
                'suggested_daily_budget'=> 1000,
                'sort_order'            => 15,
            ],
            [
                'name'                  => 'Finance & banking',
                'slug'                  => 'finance-banking',
                'industry'              => 'Finance',
                'description'           => 'Interested in loans, insurance, investments, 25–55',
                'objective'             => 'LEAD_GENERATION',
                'age_min'               => 25,
                'age_max'               => 55,
                'genders'               => 'all',
                'interests'             => json_encode([
                    ['id' => '6003107902443', 'name' => 'Finance'],
                    ['id' => '6002839319688', 'name' => 'Banking'],
                    ['id' => '6003300547473', 'name' => 'Investment'],
                ]),
                'targeting_json'        => json_encode([
                    'age_min' => 25, 'age_max' => 55,
                    'flexible_spec' => [[ 'interests' => [['id' => '6003107902443', 'name' => 'Finance']] ]],
                ]),
                'suggested_daily_budget'=> 700,
                'sort_order'            => 16,
            ],
            [
                'name'                  => 'Gamers',
                'slug'                  => 'gamers',
                'industry'              => 'Gaming',
                'description'           => 'Mobile and console gamers, 15–35',
                'objective'             => 'APP_INSTALLS',
                'age_min'               => 15,
                'age_max'               => 35,
                'genders'               => 'all',
                'interests'             => json_encode([
                    ['id' => '6003200426519', 'name' => 'Video games'],
                    ['id' => '6002839319672', 'name' => 'Mobile gaming'],
                    ['id' => '6003300547461', 'name' => 'Esports'],
                ]),
                'targeting_json'        => json_encode([
                    'age_min' => 15, 'age_max' => 35,
                    'flexible_spec' => [[ 'interests' => [['id' => '6003200426519', 'name' => 'Video games']] ]],
                ]),
                'suggested_daily_budget'=> 400,
                'sort_order'            => 17,
            ],
            [
                'name'                  => 'New parents',
                'slug'                  => 'new-parents',
                'industry'              => 'Baby & Kids',
                'description'           => 'Parents with babies or toddlers, 22–40',
                'objective'             => 'REACH',
                'age_min'               => 22,
                'age_max'               => 40,
                'genders'               => 'all',
                'behaviors'             => json_encode([['id' => '6022788483714', 'name' => 'New parents (0–12 months)']]),
                'targeting_json'        => json_encode([
                    'age_min' => 22, 'age_max' => 40,
                    'flexible_spec' => [[ 'behaviors' => [['id' => '6022788483714', 'name' => 'New parents']] ]],
                ]),
                'suggested_daily_budget'=> 400,
                'sort_order'            => 18,
            ],
            [
                'name'                  => 'Sports fans',
                'slug'                  => 'sports-fans',
                'industry'              => 'Sports',
                'description'           => 'Cricket, football, and sports lovers, 18–45',
                'objective'             => 'VIDEO_VIEWS',
                'age_min'               => 18,
                'age_max'               => 45,
                'genders'               => 'all',
                'interests'             => json_encode([
                    ['id' => '6003107902440', 'name' => 'Cricket'],
                    ['id' => '6003107902437', 'name' => 'Football'],
                    ['id' => '6003300547467', 'name' => 'Sports'],
                ]),
                'targeting_json'        => json_encode([
                    'age_min' => 18, 'age_max' => 45,
                    'flexible_spec' => [[ 'interests' => [['id' => '6003107902440', 'name' => 'Cricket']] ]],
                ]),
                'suggested_daily_budget'=> 500,
                'sort_order'            => 19,
            ],
            [
                'name'                  => 'Working professionals',
                'slug'                  => 'working-professionals',
                'industry'              => 'Professional Services',
                'description'           => 'Office workers and managers, 25–50',
                'objective'             => 'LEAD_GENERATION',
                'age_min'               => 25,
                'age_max'               => 50,
                'genders'               => 'all',
                'behaviors'             => json_encode([['id' => '6002714895370', 'name' => 'Business travellers']]),
                'interests'             => json_encode([
                    ['id' => '6003300547471', 'name' => 'Professional development'],
                    ['id' => '6002839319690', 'name' => 'Management'],
                ]),
                'targeting_json'        => json_encode([
                    'age_min' => 25, 'age_max' => 50,
                    'flexible_spec' => [[ 'interests' => [['id' => '6003300547471', 'name' => 'Professional development']] ]],
                ]),
                'suggested_daily_budget'=> 600,
                'sort_order'            => 20,
            ],
        ];

        foreach ($templates as $tpl) {
            DB::table('meta_audience_templates')->updateOrInsert(
                ['slug' => $tpl['slug']],
                array_merge($tpl, ['created_at' => now(), 'updated_at' => now()])
            );
        }

        $this->command->info('Seeded ' . count($templates) . ' Meta audience templates.');
    }
}
